export const apCredits: Map<string, string> = new Map([
  ['AP Calculus AB', 'MATH 151'],
  ['AP Calculus BC', 'MATH 151, MATH 152'],
  ['AP Computer Science A', 'COMP 110'],
  ['AP Computer Science Principles', 'COMP 110'],
  ['AP English Language and Composition', 'ENGL 105'],
  ['AP English Literature and Composition', 'ENGL 105'],
  ['AP Environmental Science', 'BIOL 101'],
  ['AP European History', 'HIST 101'],
  ['AP French Language', 'FREN 203'],
  ['AP German Language', 'GERM 203'],
  ['AP Human Geography', 'GEOG 101'],
  ['AP Macroeconomics', 'ECON 101'],
  ['AP Microeconomics', 'ECON 101'],
  ['AP Music Theory', 'MUSC 101'],
  ['AP Physics 1', 'PHYS 116'],
  ['AP Physics 2', 'PHYS 116'],
  ['AP Physics C: Electricity and Magnetism', 'PHYS 118'],
  ['AP Physics C: Mechanics', 'PHYS 116'],
  ['AP Psychology', 'PSYC 101'],
  ['AP Spanish Language', 'SPAN 203'],
  ['AP Spanish Literature', 'SPAN 203'],
  ['AP Statistics', 'MATH 233'],
  ['AP United States Government and Politics', 'POLS 101'],
  ['AP United States History', 'HIST 131, HIST 132'],
  ['AP World History', 'HIST 101, HIST 102']
]);