/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { IMyContext } from "./../src/interface"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  AddClassToDegreeScheduleInput: { // input type
    classId: number; // Int!
    degreeScheduleId: number; // Int!
  }
  AddClassToScheduleInput: { // input type
    classId: number; // Int!
    classScheduleId: number; // Int!
  }
  CreateClassInput: { // input type
    classCode: string; // String!
    color: string; // String!
    coreDegreeId: number; // Int!
    courseType: string; // String!
    dayOfWeek: string; // String!
    electiveDegreeId: Array<number | null>; // [Int]!
    endTime: string; // String!
    professor: string; // String!
    rateMyProfessorRating: number; // Float!
    startTime: string; // String!
    title: string; // String!
  }
  CreateClassScheduleInput: { // input type
    semesterId: number; // Int!
    userId: string; // String!
  }
  CreateDegreeInput: { // input type
    name: string; // String!
    numberOfCores: number; // Int!
    numberOfElectives: number; // Int!
  }
  CreateDegreeScheduleInput: { // input type
    degreeId: number; // Int!
    semesterId: number; // Int!
    userId: string; // String!
  }
  CreateTaskInput: { // input type
    task?: NexusGenInputs['TaskInputFields'] | null; // TaskInputFields
  }
  DeleteClassInput: { // input type
    id: number; // Int!
  }
  DeleteDegreeInput: { // input type
    id: number; // Int!
  }
  DeleteTaskInput: { // input type
    id: number; // Int!
  }
  LoginInput: { // input type
    email: string; // String!
    password: string; // String!
  }
  RegisterInput: { // input type
    email: string; // String!
    password: string; // String!
  }
  RemoveClassFromDegreeScheduleInput: { // input type
    id: number; // Int!
  }
  RemoveClassFromScheduleInput: { // input type
    id: number; // Int!
  }
  TaskInputFields: { // input type
    classCode?: string | null; // String
    description?: string | null; // String
    dueDate: string; // String!
    stageId?: number | null; // Int
    title: string; // String!
    userId: string; // String!
  }
  UpdateClassInput: { // input type
    classCode?: string | null; // String
    color?: string | null; // String
    coreDegreeId?: number | null; // Int
    courseType?: string | null; // String
    dayOfWeek?: string | null; // String
    electiveDegreeId?: Array<number | null> | null; // [Int]
    endTime?: string | null; // String
    id: number; // Int!
    professor?: string | null; // String
    rateMyProfessorRating?: number | null; // Float
    startTime?: string | null; // String
    title?: string | null; // String
  }
  UpdateClassScheduleInput: { // input type
    id: number; // Int!
    semesterId?: number | null; // Int
  }
  UpdateDegreeInput: { // input type
    id: number; // Int!
    name?: string | null; // String
    numberOfCores?: number | null; // Int
    numberOfElectives?: number | null; // Int
  }
  UpdateDegreeScheduleInput: { // input type
    id: number; // Int!
    semesterId?: number | null; // Int
  }
  UpdateTaskFields: { // input type
    classCode?: string | null; // String
    description?: string | null; // String
    dueDate?: string | null; // String
    id: number; // Int!
    stageId?: number | null; // Int
    title?: string | null; // String
  }
  UpdateTaskInput: { // input type
    id: number; // Int!
    update?: NexusGenInputs['UpdateTaskFields'] | null; // UpdateTaskFields
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Class: { // root type
    classCode: string; // String!
    classSchedules?: Array<NexusGenRootTypes['ClassSchedule'] | null> | null; // [ClassSchedule]
    color: string; // String!
    coreDegreeId: number; // Int!
    courseType: string; // String!
    dayOfWeek: string; // String!
    electiveDegreeId?: Array<number | null> | null; // [Int]
    endTime: string; // String!
    id: number; // Int!
    professor: string; // String!
    rateMyProfessorRating: number; // Float!
    startTime: string; // String!
    title: string; // String!
  }
  ClassSchedule: { // root type
    entries?: Array<NexusGenRootTypes['ClassScheduleEntry'] | null> | null; // [ClassScheduleEntry]
    id: number; // Int!
    semesterId: number; // Int!
    user?: NexusGenRootTypes['User'] | null; // User
    userId: string; // String!
  }
  ClassScheduleEntry: { // root type
    class?: NexusGenRootTypes['Class'] | null; // Class
    classId: number; // Int!
    classSchedule?: NexusGenRootTypes['ClassSchedule'] | null; // ClassSchedule
    classScheduleId: number; // Int!
    id: number; // Int!
  }
  Degree: { // root type
    degreeSchedules?: Array<NexusGenRootTypes['DegreeSchedule'] | null> | null; // [DegreeSchedule]
    id: number; // Int!
    name: string; // String!
    numberOfCores: number; // Int!
    numberOfElectives: number; // Int!
    users?: Array<NexusGenRootTypes['User'] | null> | null; // [User]
  }
  DegreeSchedule: { // root type
    degree?: NexusGenRootTypes['Degree'] | null; // Degree
    degreeId: number; // Int!
    entries?: Array<NexusGenRootTypes['DegreeScheduleEntry'] | null> | null; // [DegreeScheduleEntry]
    id: number; // Int!
    semesterId: number; // Int!
    user?: NexusGenRootTypes['User'] | null; // User
    userId: string; // String!
  }
  DegreeScheduleEntry: { // root type
    class?: NexusGenRootTypes['Class'] | null; // Class
    classId: number; // Int!
    degreeSchedule?: NexusGenRootTypes['DegreeSchedule'] | null; // DegreeSchedule
    degreeScheduleId: number; // Int!
    id: number; // Int!
  }
  Mutation: {};
  Query: {};
  Task: { // root type
    classCode?: string | null; // String
    description?: string | null; // String
    dueDate: string; // String!
    id: number; // Int!
    stageId: number; // Int!
    title: string; // String!
    user?: NexusGenRootTypes['User'] | null; // User
    userId: string; // String!
  }
  User: { // root type
    assignmentCompletionPercentage?: number | null; // Float
    attendancePercentage?: number | null; // Float
    classSchedules?: Array<NexusGenRootTypes['ClassSchedule'] | null> | null; // [ClassSchedule]
    degree?: NexusGenRootTypes['Degree'] | null; // Degree
    degreeId?: number | null; // Int
    degreeSchedules?: Array<NexusGenRootTypes['DegreeSchedule'] | null> | null; // [DegreeSchedule]
    email: string; // String!
    gpa?: number | null; // Float
    id: string; // String!
    tasks?: Array<NexusGenRootTypes['Task'] | null> | null; // [Task]
    university?: string | null; // String
    yearInUniversity?: number | null; // Int
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Class: { // field return type
    classCode: string; // String!
    classSchedules: Array<NexusGenRootTypes['ClassSchedule'] | null> | null; // [ClassSchedule]
    color: string; // String!
    coreDegreeId: number; // Int!
    courseType: string; // String!
    dayOfWeek: string; // String!
    electiveDegreeId: Array<number | null> | null; // [Int]
    endTime: string; // String!
    id: number; // Int!
    professor: string; // String!
    rateMyProfessorRating: number; // Float!
    startTime: string; // String!
    title: string; // String!
  }
  ClassSchedule: { // field return type
    entries: Array<NexusGenRootTypes['ClassScheduleEntry'] | null> | null; // [ClassScheduleEntry]
    id: number; // Int!
    semesterId: number; // Int!
    user: NexusGenRootTypes['User'] | null; // User
    userId: string; // String!
  }
  ClassScheduleEntry: { // field return type
    class: NexusGenRootTypes['Class'] | null; // Class
    classId: number; // Int!
    classSchedule: NexusGenRootTypes['ClassSchedule'] | null; // ClassSchedule
    classScheduleId: number; // Int!
    id: number; // Int!
  }
  Degree: { // field return type
    degreeSchedules: Array<NexusGenRootTypes['DegreeSchedule'] | null> | null; // [DegreeSchedule]
    id: number; // Int!
    name: string; // String!
    numberOfCores: number; // Int!
    numberOfElectives: number; // Int!
    users: Array<NexusGenRootTypes['User'] | null> | null; // [User]
  }
  DegreeSchedule: { // field return type
    degree: NexusGenRootTypes['Degree'] | null; // Degree
    degreeId: number; // Int!
    entries: Array<NexusGenRootTypes['DegreeScheduleEntry'] | null> | null; // [DegreeScheduleEntry]
    id: number; // Int!
    semesterId: number; // Int!
    user: NexusGenRootTypes['User'] | null; // User
    userId: string; // String!
  }
  DegreeScheduleEntry: { // field return type
    class: NexusGenRootTypes['Class'] | null; // Class
    classId: number; // Int!
    degreeSchedule: NexusGenRootTypes['DegreeSchedule'] | null; // DegreeSchedule
    degreeScheduleId: number; // Int!
    id: number; // Int!
  }
  Mutation: { // field return type
    addClassToClassSchedule: NexusGenRootTypes['ClassScheduleEntry'] | null; // ClassScheduleEntry
    addClassToDegreeSchedule: NexusGenRootTypes['DegreeScheduleEntry'] | null; // DegreeScheduleEntry
    createClass: NexusGenRootTypes['Class'] | null; // Class
    createClassSchedule: NexusGenRootTypes['ClassSchedule'] | null; // ClassSchedule
    createDegree: NexusGenRootTypes['Degree'] | null; // Degree
    createDegreeSchedule: NexusGenRootTypes['DegreeSchedule'] | null; // DegreeSchedule
    createTask: NexusGenRootTypes['Task'] | null; // Task
    deleteClass: NexusGenRootTypes['Class'] | null; // Class
    deleteClassSchedule: NexusGenRootTypes['ClassSchedule'] | null; // ClassSchedule
    deleteDegree: NexusGenRootTypes['Degree'] | null; // Degree
    deleteDegreeSchedule: NexusGenRootTypes['DegreeSchedule'] | null; // DegreeSchedule
    deleteTask: NexusGenRootTypes['Task'] | null; // Task
    login: string | null; // String
    logout: boolean | null; // Boolean
    register: string | null; // String
    removeClassFromClassSchedule: NexusGenRootTypes['ClassScheduleEntry'] | null; // ClassScheduleEntry
    removeClassFromDegreeSchedule: NexusGenRootTypes['DegreeScheduleEntry'] | null; // DegreeScheduleEntry
    updateClass: NexusGenRootTypes['Class'] | null; // Class
    updateClassSchedule: NexusGenRootTypes['ClassSchedule'] | null; // ClassSchedule
    updateDegree: NexusGenRootTypes['Degree'] | null; // Degree
    updateDegreeSchedule: NexusGenRootTypes['DegreeSchedule'] | null; // DegreeSchedule
    updateTask: NexusGenRootTypes['Task'] | null; // Task
    updateUserAcademicInfo: NexusGenRootTypes['User'] | null; // User
    updateUserProfile: NexusGenRootTypes['User'] | null; // User
  }
  Query: { // field return type
    getAllDegrees: Array<NexusGenRootTypes['Degree'] | null> | null; // [Degree]
    getClass: NexusGenRootTypes['Class'] | null; // Class
    getClassScheduleEntries: Array<NexusGenRootTypes['ClassScheduleEntry'] | null> | null; // [ClassScheduleEntry]
    getClassSchedules: Array<NexusGenRootTypes['ClassSchedule'] | null> | null; // [ClassSchedule]
    getClasses: Array<NexusGenRootTypes['Class'] | null> | null; // [Class]
    getDegree: NexusGenRootTypes['Degree'] | null; // Degree
    getDegreeScheduleEntries: Array<NexusGenRootTypes['DegreeScheduleEntry'] | null> | null; // [DegreeScheduleEntry]
    getDegreeSchedules: Array<NexusGenRootTypes['DegreeSchedule'] | null> | null; // [DegreeSchedule]
    getTasks: Array<NexusGenRootTypes['Task'] | null> | null; // [Task]
    getUser: NexusGenRootTypes['User'] | null; // User
  }
  Task: { // field return type
    classCode: string | null; // String
    description: string | null; // String
    dueDate: string; // String!
    id: number; // Int!
    stageId: number; // Int!
    title: string; // String!
    user: NexusGenRootTypes['User'] | null; // User
    userId: string; // String!
  }
  User: { // field return type
    assignmentCompletionPercentage: number | null; // Float
    attendancePercentage: number | null; // Float
    classSchedules: Array<NexusGenRootTypes['ClassSchedule'] | null> | null; // [ClassSchedule]
    degree: NexusGenRootTypes['Degree'] | null; // Degree
    degreeId: number | null; // Int
    degreeSchedules: Array<NexusGenRootTypes['DegreeSchedule'] | null> | null; // [DegreeSchedule]
    email: string; // String!
    gpa: number | null; // Float
    id: string; // String!
    tasks: Array<NexusGenRootTypes['Task'] | null> | null; // [Task]
    university: string | null; // String
    yearInUniversity: number | null; // Int
  }
}

export interface NexusGenFieldTypeNames {
  Class: { // field return type name
    classCode: 'String'
    classSchedules: 'ClassSchedule'
    color: 'String'
    coreDegreeId: 'Int'
    courseType: 'String'
    dayOfWeek: 'String'
    electiveDegreeId: 'Int'
    endTime: 'String'
    id: 'Int'
    professor: 'String'
    rateMyProfessorRating: 'Float'
    startTime: 'String'
    title: 'String'
  }
  ClassSchedule: { // field return type name
    entries: 'ClassScheduleEntry'
    id: 'Int'
    semesterId: 'Int'
    user: 'User'
    userId: 'String'
  }
  ClassScheduleEntry: { // field return type name
    class: 'Class'
    classId: 'Int'
    classSchedule: 'ClassSchedule'
    classScheduleId: 'Int'
    id: 'Int'
  }
  Degree: { // field return type name
    degreeSchedules: 'DegreeSchedule'
    id: 'Int'
    name: 'String'
    numberOfCores: 'Int'
    numberOfElectives: 'Int'
    users: 'User'
  }
  DegreeSchedule: { // field return type name
    degree: 'Degree'
    degreeId: 'Int'
    entries: 'DegreeScheduleEntry'
    id: 'Int'
    semesterId: 'Int'
    user: 'User'
    userId: 'String'
  }
  DegreeScheduleEntry: { // field return type name
    class: 'Class'
    classId: 'Int'
    degreeSchedule: 'DegreeSchedule'
    degreeScheduleId: 'Int'
    id: 'Int'
  }
  Mutation: { // field return type name
    addClassToClassSchedule: 'ClassScheduleEntry'
    addClassToDegreeSchedule: 'DegreeScheduleEntry'
    createClass: 'Class'
    createClassSchedule: 'ClassSchedule'
    createDegree: 'Degree'
    createDegreeSchedule: 'DegreeSchedule'
    createTask: 'Task'
    deleteClass: 'Class'
    deleteClassSchedule: 'ClassSchedule'
    deleteDegree: 'Degree'
    deleteDegreeSchedule: 'DegreeSchedule'
    deleteTask: 'Task'
    login: 'String'
    logout: 'Boolean'
    register: 'String'
    removeClassFromClassSchedule: 'ClassScheduleEntry'
    removeClassFromDegreeSchedule: 'DegreeScheduleEntry'
    updateClass: 'Class'
    updateClassSchedule: 'ClassSchedule'
    updateDegree: 'Degree'
    updateDegreeSchedule: 'DegreeSchedule'
    updateTask: 'Task'
    updateUserAcademicInfo: 'User'
    updateUserProfile: 'User'
  }
  Query: { // field return type name
    getAllDegrees: 'Degree'
    getClass: 'Class'
    getClassScheduleEntries: 'ClassScheduleEntry'
    getClassSchedules: 'ClassSchedule'
    getClasses: 'Class'
    getDegree: 'Degree'
    getDegreeScheduleEntries: 'DegreeScheduleEntry'
    getDegreeSchedules: 'DegreeSchedule'
    getTasks: 'Task'
    getUser: 'User'
  }
  Task: { // field return type name
    classCode: 'String'
    description: 'String'
    dueDate: 'String'
    id: 'Int'
    stageId: 'Int'
    title: 'String'
    user: 'User'
    userId: 'String'
  }
  User: { // field return type name
    assignmentCompletionPercentage: 'Float'
    attendancePercentage: 'Float'
    classSchedules: 'ClassSchedule'
    degree: 'Degree'
    degreeId: 'Int'
    degreeSchedules: 'DegreeSchedule'
    email: 'String'
    gpa: 'Float'
    id: 'String'
    tasks: 'Task'
    university: 'String'
    yearInUniversity: 'Int'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addClassToClassSchedule: { // args
      input: NexusGenInputs['AddClassToScheduleInput']; // AddClassToScheduleInput!
    }
    addClassToDegreeSchedule: { // args
      input: NexusGenInputs['AddClassToDegreeScheduleInput']; // AddClassToDegreeScheduleInput!
    }
    createClass: { // args
      input: NexusGenInputs['CreateClassInput']; // CreateClassInput!
    }
    createClassSchedule: { // args
      input: NexusGenInputs['CreateClassScheduleInput']; // CreateClassScheduleInput!
    }
    createDegree: { // args
      input: NexusGenInputs['CreateDegreeInput']; // CreateDegreeInput!
    }
    createDegreeSchedule: { // args
      input: NexusGenInputs['CreateDegreeScheduleInput']; // CreateDegreeScheduleInput!
    }
    createTask: { // args
      input?: NexusGenInputs['CreateTaskInput'] | null; // CreateTaskInput
    }
    deleteClass: { // args
      input: NexusGenInputs['DeleteClassInput']; // DeleteClassInput!
    }
    deleteClassSchedule: { // args
      id: number; // Int!
    }
    deleteDegree: { // args
      input: NexusGenInputs['DeleteDegreeInput']; // DeleteDegreeInput!
    }
    deleteDegreeSchedule: { // args
      id: number; // Int!
    }
    deleteTask: { // args
      input?: NexusGenInputs['DeleteTaskInput'] | null; // DeleteTaskInput
    }
    login: { // args
      input: NexusGenInputs['LoginInput']; // LoginInput!
    }
    register: { // args
      input: NexusGenInputs['RegisterInput']; // RegisterInput!
    }
    removeClassFromClassSchedule: { // args
      input: NexusGenInputs['RemoveClassFromScheduleInput']; // RemoveClassFromScheduleInput!
    }
    removeClassFromDegreeSchedule: { // args
      input: NexusGenInputs['RemoveClassFromDegreeScheduleInput']; // RemoveClassFromDegreeScheduleInput!
    }
    updateClass: { // args
      input: NexusGenInputs['UpdateClassInput']; // UpdateClassInput!
    }
    updateClassSchedule: { // args
      input: NexusGenInputs['UpdateClassScheduleInput']; // UpdateClassScheduleInput!
    }
    updateDegree: { // args
      input: NexusGenInputs['UpdateDegreeInput']; // UpdateDegreeInput!
    }
    updateDegreeSchedule: { // args
      input: NexusGenInputs['UpdateDegreeScheduleInput']; // UpdateDegreeScheduleInput!
    }
    updateTask: { // args
      input?: NexusGenInputs['UpdateTaskInput'] | null; // UpdateTaskInput
    }
    updateUserAcademicInfo: { // args
      assignmentCompletionPercentage?: number | null; // Float
      attendancePercentage?: number | null; // Float
      gpa?: number | null; // Float
      id: string; // String!
    }
    updateUserProfile: { // args
      degreeId: number; // Int!
      id: string; // String!
      university: string; // String!
      yearInUniversity: number; // Int!
    }
  }
  Query: {
    getClass: { // args
      id: number; // Int!
    }
    getClassScheduleEntries: { // args
      classScheduleId: number; // Int!
    }
    getClassSchedules: { // args
      userId: string; // String!
    }
    getDegree: { // args
      id: number; // Int!
    }
    getDegreeScheduleEntries: { // args
      degreeScheduleId: number; // Int!
    }
    getDegreeSchedules: { // args
      userId: string; // String!
    }
    getTasks: { // args
      userId: string; // String!
    }
    getUser: { // args
      id: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: IMyContext;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}