/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { IMyContext } from "./../src/interface"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CreateClassInput: { // input type
    classCode: string; // String!
    color: string; // String!
    coreDegreeId: number; // Int!
    courseType: string; // String!
    credits: number; // Int!
    dayOfWeek: string; // String!
    description: string; // String!
    electiveDegreeId: Array<number | null>; // [Int]!
    endTime: string; // String!
    professor: string; // String!
    rateMyProfessorRating: number; // Float!
    startTime: string; // String!
    title: string; // String!
  }
  LoginInput: { // input type
    email: string; // String!
    password: string; // String!
  }
  RegisterInput: { // input type
    email: string; // String!
    password: string; // String!
  }
  UpdateClassInput: { // input type
    classCode?: string | null; // String
    color?: string | null; // String
    coreDegreeId?: number | null; // Int
    courseType?: string | null; // String
    credits?: number | null; // Int
    dayOfWeek?: string | null; // String
    description?: string | null; // String
    electiveDegreeId?: Array<number | null> | null; // [Int]
    endTime?: string | null; // String
    id: number; // Int!
    professor?: string | null; // String
    rateMyProfessorRating?: number | null; // Float
    startTime?: string | null; // String
    title?: string | null; // String
  }
  addClassToScheduleInput: { // input type
    classId: number; // Int!
    classScheduleId: number; // Int!
  }
  addClassToSemesterInput: { // input type
    classId: number; // Int!
    credits: number; // Int!
    semesterId: number; // Int!
  }
  createClassScheduleInput: { // input type
    semesterId: string; // String!
    userId: string; // String!
  }
  createDegreeInput: { // input type
    name: string; // String!
    numberOfCores: number; // Int!
    numberOfElectives: number; // Int!
  }
  createDegreePlannerInput: { // input type
    degreeId: number; // Int!
    userId: string; // String!
  }
  createSemesterInput: { // input type
    classIds?: number[] | null; // [Int!]
    degreeId: number; // Int!
    name: string; // String!
    plannerId: number; // Int!
  }
  createTaskInput: { // input type
    task?: NexusGenInputs['taskInputFields'] | null; // taskInputFields
  }
  deleteClassInput: { // input type
    id: number; // Int!
  }
  deleteDegreeInput: { // input type
    id: number; // Int!
  }
  deleteTaskInput: { // input type
    id: number; // Int!
  }
  removeClassFromScheduleInput: { // input type
    id: number; // Int!
  }
  removeClassFromSemesterInput: { // input type
    classId: number; // Int!
    credits: number; // Int!
    semesterId: number; // Int!
  }
  semesterEntryInput: { // input type
    classId: number; // Int!
    index: number; // Int!
  }
  taskInputFields: { // input type
    classCode?: string | null; // String
    description?: string | null; // String
    dueDate: string; // String!
    stageId?: number | null; // Int
    title: string; // String!
    userId: string; // String!
  }
  updateClassScheduleInput: { // input type
    id: number; // Int!
    semesterId?: string | null; // String
  }
  updateDegreeInput: { // input type
    id: number; // Int!
    name?: string | null; // String
    numberOfCores?: number | null; // Int
    numberOfElectives?: number | null; // Int
  }
  updateSemesterInput: { // input type
    credits: number; // Int!
    entries?: NexusGenInputs['semesterEntryInput'][] | null; // [semesterEntryInput!]
    id: number; // Int!
    name?: string | null; // String
  }
  updateTaskFields: { // input type
    classCode?: string | null; // String
    description?: string | null; // String
    dueDate?: string | null; // String
    id: number; // Int!
    stageId?: number | null; // Int
    title?: string | null; // String
  }
  updateTaskInput: { // input type
    id: number; // Int!
    update?: NexusGenInputs['updateTaskFields'] | null; // updateTaskFields
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Class: { // root type
    classCode: string; // String!
    classSchedules?: Array<NexusGenRootTypes['classSchedule'] | null> | null; // [classSchedule]
    color: string; // String!
    coreDegreeId: Array<number | null>; // [Int]!
    courseType: string; // String!
    credits: number; // Int!
    dayOfWeek: string; // String!
    description: string; // String!
    electiveDegreeId?: Array<number | null> | null; // [Int]
    endTime: string; // String!
    id: number; // Int!
    professor: string; // String!
    rateMyProfessorRating: number; // Float!
    startTime: string; // String!
    title: string; // String!
  }
  Mutation: {};
  Query: {};
  classSchedule: { // root type
    entries?: Array<NexusGenRootTypes['classScheduleEntry'] | null> | null; // [classScheduleEntry]
    id: number; // Int!
    semesterId: string; // String!
    user?: NexusGenRootTypes['user'] | null; // user
    userId: string; // String!
  }
  classScheduleEntry: { // root type
    class?: NexusGenRootTypes['Class'] | null; // Class
    classId: number; // Int!
    classSchedule?: NexusGenRootTypes['classSchedule'] | null; // classSchedule
    classScheduleId: number; // Int!
    id: number; // Int!
  }
  degree: { // root type
    id: number; // Int!
    name: string; // String!
    numberOfCores: number; // Int!
    numberOfElectives: number; // Int!
    semesters?: Array<NexusGenRootTypes['semester'] | null> | null; // [semester]
    users?: Array<NexusGenRootTypes['user'] | null> | null; // [user]
  }
  degreePlanner: { // root type
    degree?: NexusGenRootTypes['degree'] | null; // degree
    degreeId: number; // Int!
    id: number; // Int!
    semester?: Array<NexusGenRootTypes['semester'] | null> | null; // [semester]
    user?: NexusGenRootTypes['user'] | null; // user
    userId: string; // String!
  }
  semester: { // root type
    credits: number; // Int!
    degreeId: number; // Int!
    degreePlanner?: NexusGenRootTypes['degreePlanner'] | null; // degreePlanner
    entries?: Array<NexusGenRootTypes['semesterEntry'] | null> | null; // [semesterEntry]
    id: number; // Int!
    name: string; // String!
    plannerId: number; // Int!
  }
  semesterEntry: { // root type
    class?: NexusGenRootTypes['Class'] | null; // Class
    classId: number; // Int!
    id: number; // Int!
    index: number; // Int!
    semester?: NexusGenRootTypes['semester'] | null; // semester
    semesterId: number; // Int!
  }
  task: { // root type
    classCode?: string | null; // String
    description?: string | null; // String
    dueDate: string; // String!
    id: number; // Int!
    stageId: number; // Int!
    title: string; // String!
    user?: NexusGenRootTypes['user'] | null; // user
    userId: string; // String!
  }
  user: { // root type
    assignmentCompletionPercentage?: number | null; // Float
    attendancePercentage?: number | null; // Float
    classSchedules?: Array<NexusGenRootTypes['classSchedule'] | null> | null; // [classSchedule]
    degree?: NexusGenRootTypes['degree'] | null; // degree
    degreeId?: number | null; // Int
    degreePlanners?: Array<NexusGenRootTypes['degreePlanner'] | null> | null; // [degreePlanner]
    email: string; // String!
    gpa?: number | null; // Float
    id: string; // String!
    takenClassIds?: Array<number | null> | null; // [Int]
    tasks?: Array<NexusGenRootTypes['task'] | null> | null; // [task]
    university?: string | null; // String
    yearInUniversity?: number | null; // Int
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Class: { // field return type
    classCode: string; // String!
    classSchedules: Array<NexusGenRootTypes['classSchedule'] | null> | null; // [classSchedule]
    color: string; // String!
    coreDegreeId: Array<number | null>; // [Int]!
    courseType: string; // String!
    credits: number; // Int!
    dayOfWeek: string; // String!
    description: string; // String!
    electiveDegreeId: Array<number | null> | null; // [Int]
    endTime: string; // String!
    id: number; // Int!
    professor: string; // String!
    rateMyProfessorRating: number; // Float!
    startTime: string; // String!
    title: string; // String!
  }
  Mutation: { // field return type
    addClassToClassSchedule: NexusGenRootTypes['classScheduleEntry'] | null; // classScheduleEntry
    addClassTosemester: NexusGenRootTypes['semesterEntry'] | null; // semesterEntry
    createClass: NexusGenRootTypes['Class'] | null; // Class
    createClassSchedule: NexusGenRootTypes['classSchedule'] | null; // classSchedule
    createDegree: NexusGenRootTypes['degree'] | null; // degree
    createDegreePlanner: NexusGenRootTypes['degreePlanner'] | null; // degreePlanner
    createSemester: NexusGenRootTypes['semester'] | null; // semester
    createTask: NexusGenRootTypes['task'] | null; // task
    deleteClass: NexusGenRootTypes['Class'] | null; // Class
    deleteClassSchedule: NexusGenRootTypes['classSchedule'] | null; // classSchedule
    deleteDegree: NexusGenRootTypes['degree'] | null; // degree
    deleteDegreePlanner: NexusGenRootTypes['degreePlanner'] | null; // degreePlanner
    deleteTask: NexusGenRootTypes['task'] | null; // task
    deletesemester: NexusGenRootTypes['semester'] | null; // semester
    login: string | null; // String
    logout: boolean | null; // Boolean
    register: string | null; // String
    removeClassFromClassSchedule: NexusGenRootTypes['classScheduleEntry'] | null; // classScheduleEntry
    removeClassFromsemester: NexusGenRootTypes['semesterEntry'] | null; // semesterEntry
    updateClass: NexusGenRootTypes['Class'] | null; // Class
    updateClassSchedule: NexusGenRootTypes['classSchedule'] | null; // classSchedule
    updateDegree: NexusGenRootTypes['degree'] | null; // degree
    updateSemester: NexusGenRootTypes['semester'] | null; // semester
    updateTask: NexusGenRootTypes['task'] | null; // task
    updateUserAcademicInfo: NexusGenRootTypes['user'] | null; // user
    updateUserProfile: NexusGenRootTypes['user'] | null; // user
  }
  Query: { // field return type
    getAlldegrees: Array<NexusGenRootTypes['degree'] | null> | null; // [degree]
    getClass: NexusGenRootTypes['Class'] | null; // Class
    getClassScheduleEntries: Array<NexusGenRootTypes['classScheduleEntry'] | null> | null; // [classScheduleEntry]
    getClasses: Array<NexusGenRootTypes['Class'] | null> | null; // [Class]
    getDegree: NexusGenRootTypes['degree'] | null; // degree
    getDegreeRequirements: NexusGenRootTypes['degree'] | null; // degree
    getSemester: NexusGenRootTypes['semester'] | null; // semester
    getTasks: Array<NexusGenRootTypes['task'] | null> | null; // [task]
    getUser: NexusGenRootTypes['user'] | null; // user
    getclassSchedules: Array<NexusGenRootTypes['classSchedule'] | null> | null; // [classSchedule]
    getdegreePlanners: Array<NexusGenRootTypes['degreePlanner'] | null> | null; // [degreePlanner]
    getsemesters: Array<NexusGenRootTypes['semester'] | null> | null; // [semester]
  }
  classSchedule: { // field return type
    entries: Array<NexusGenRootTypes['classScheduleEntry'] | null> | null; // [classScheduleEntry]
    id: number; // Int!
    semesterId: string; // String!
    user: NexusGenRootTypes['user'] | null; // user
    userId: string; // String!
  }
  classScheduleEntry: { // field return type
    class: NexusGenRootTypes['Class'] | null; // Class
    classId: number; // Int!
    classSchedule: NexusGenRootTypes['classSchedule'] | null; // classSchedule
    classScheduleId: number; // Int!
    id: number; // Int!
  }
  degree: { // field return type
    id: number; // Int!
    name: string; // String!
    numberOfCores: number; // Int!
    numberOfElectives: number; // Int!
    semesters: Array<NexusGenRootTypes['semester'] | null> | null; // [semester]
    users: Array<NexusGenRootTypes['user'] | null> | null; // [user]
  }
  degreePlanner: { // field return type
    degree: NexusGenRootTypes['degree'] | null; // degree
    degreeId: number; // Int!
    id: number; // Int!
    semester: Array<NexusGenRootTypes['semester'] | null> | null; // [semester]
    user: NexusGenRootTypes['user'] | null; // user
    userId: string; // String!
  }
  semester: { // field return type
    credits: number; // Int!
    degreeId: number; // Int!
    degreePlanner: NexusGenRootTypes['degreePlanner'] | null; // degreePlanner
    entries: Array<NexusGenRootTypes['semesterEntry'] | null> | null; // [semesterEntry]
    id: number; // Int!
    name: string; // String!
    plannerId: number; // Int!
  }
  semesterEntry: { // field return type
    class: NexusGenRootTypes['Class'] | null; // Class
    classId: number; // Int!
    id: number; // Int!
    index: number; // Int!
    semester: NexusGenRootTypes['semester'] | null; // semester
    semesterId: number; // Int!
  }
  task: { // field return type
    classCode: string | null; // String
    description: string | null; // String
    dueDate: string; // String!
    id: number; // Int!
    stageId: number; // Int!
    title: string; // String!
    user: NexusGenRootTypes['user'] | null; // user
    userId: string; // String!
  }
  user: { // field return type
    assignmentCompletionPercentage: number | null; // Float
    attendancePercentage: number | null; // Float
    classSchedules: Array<NexusGenRootTypes['classSchedule'] | null> | null; // [classSchedule]
    degree: NexusGenRootTypes['degree'] | null; // degree
    degreeId: number | null; // Int
    degreePlanners: Array<NexusGenRootTypes['degreePlanner'] | null> | null; // [degreePlanner]
    email: string; // String!
    gpa: number | null; // Float
    id: string; // String!
    takenClassIds: Array<number | null> | null; // [Int]
    tasks: Array<NexusGenRootTypes['task'] | null> | null; // [task]
    university: string | null; // String
    yearInUniversity: number | null; // Int
  }
}

export interface NexusGenFieldTypeNames {
  Class: { // field return type name
    classCode: 'String'
    classSchedules: 'classSchedule'
    color: 'String'
    coreDegreeId: 'Int'
    courseType: 'String'
    credits: 'Int'
    dayOfWeek: 'String'
    description: 'String'
    electiveDegreeId: 'Int'
    endTime: 'String'
    id: 'Int'
    professor: 'String'
    rateMyProfessorRating: 'Float'
    startTime: 'String'
    title: 'String'
  }
  Mutation: { // field return type name
    addClassToClassSchedule: 'classScheduleEntry'
    addClassTosemester: 'semesterEntry'
    createClass: 'Class'
    createClassSchedule: 'classSchedule'
    createDegree: 'degree'
    createDegreePlanner: 'degreePlanner'
    createSemester: 'semester'
    createTask: 'task'
    deleteClass: 'Class'
    deleteClassSchedule: 'classSchedule'
    deleteDegree: 'degree'
    deleteDegreePlanner: 'degreePlanner'
    deleteTask: 'task'
    deletesemester: 'semester'
    login: 'String'
    logout: 'Boolean'
    register: 'String'
    removeClassFromClassSchedule: 'classScheduleEntry'
    removeClassFromsemester: 'semesterEntry'
    updateClass: 'Class'
    updateClassSchedule: 'classSchedule'
    updateDegree: 'degree'
    updateSemester: 'semester'
    updateTask: 'task'
    updateUserAcademicInfo: 'user'
    updateUserProfile: 'user'
  }
  Query: { // field return type name
    getAlldegrees: 'degree'
    getClass: 'Class'
    getClassScheduleEntries: 'classScheduleEntry'
    getClasses: 'Class'
    getDegree: 'degree'
    getDegreeRequirements: 'degree'
    getSemester: 'semester'
    getTasks: 'task'
    getUser: 'user'
    getclassSchedules: 'classSchedule'
    getdegreePlanners: 'degreePlanner'
    getsemesters: 'semester'
  }
  classSchedule: { // field return type name
    entries: 'classScheduleEntry'
    id: 'Int'
    semesterId: 'String'
    user: 'user'
    userId: 'String'
  }
  classScheduleEntry: { // field return type name
    class: 'Class'
    classId: 'Int'
    classSchedule: 'classSchedule'
    classScheduleId: 'Int'
    id: 'Int'
  }
  degree: { // field return type name
    id: 'Int'
    name: 'String'
    numberOfCores: 'Int'
    numberOfElectives: 'Int'
    semesters: 'semester'
    users: 'user'
  }
  degreePlanner: { // field return type name
    degree: 'degree'
    degreeId: 'Int'
    id: 'Int'
    semester: 'semester'
    user: 'user'
    userId: 'String'
  }
  semester: { // field return type name
    credits: 'Int'
    degreeId: 'Int'
    degreePlanner: 'degreePlanner'
    entries: 'semesterEntry'
    id: 'Int'
    name: 'String'
    plannerId: 'Int'
  }
  semesterEntry: { // field return type name
    class: 'Class'
    classId: 'Int'
    id: 'Int'
    index: 'Int'
    semester: 'semester'
    semesterId: 'Int'
  }
  task: { // field return type name
    classCode: 'String'
    description: 'String'
    dueDate: 'String'
    id: 'Int'
    stageId: 'Int'
    title: 'String'
    user: 'user'
    userId: 'String'
  }
  user: { // field return type name
    assignmentCompletionPercentage: 'Float'
    attendancePercentage: 'Float'
    classSchedules: 'classSchedule'
    degree: 'degree'
    degreeId: 'Int'
    degreePlanners: 'degreePlanner'
    email: 'String'
    gpa: 'Float'
    id: 'String'
    takenClassIds: 'Int'
    tasks: 'task'
    university: 'String'
    yearInUniversity: 'Int'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addClassToClassSchedule: { // args
      input: NexusGenInputs['addClassToScheduleInput']; // addClassToScheduleInput!
    }
    addClassTosemester: { // args
      input: NexusGenInputs['addClassToSemesterInput']; // addClassToSemesterInput!
    }
    createClass: { // args
      input: NexusGenInputs['CreateClassInput']; // CreateClassInput!
    }
    createClassSchedule: { // args
      input: NexusGenInputs['createClassScheduleInput']; // createClassScheduleInput!
    }
    createDegree: { // args
      input: NexusGenInputs['createDegreeInput']; // createDegreeInput!
    }
    createDegreePlanner: { // args
      input: NexusGenInputs['createDegreePlannerInput']; // createDegreePlannerInput!
    }
    createSemester: { // args
      input: NexusGenInputs['createSemesterInput']; // createSemesterInput!
    }
    createTask: { // args
      input?: NexusGenInputs['createTaskInput'] | null; // createTaskInput
    }
    deleteClass: { // args
      input: NexusGenInputs['deleteClassInput']; // deleteClassInput!
    }
    deleteClassSchedule: { // args
      id: number; // Int!
    }
    deleteDegree: { // args
      input: NexusGenInputs['deleteDegreeInput']; // deleteDegreeInput!
    }
    deleteDegreePlanner: { // args
      id: number; // Int!
    }
    deleteTask: { // args
      input?: NexusGenInputs['deleteTaskInput'] | null; // deleteTaskInput
    }
    deletesemester: { // args
      id: number; // Int!
    }
    login: { // args
      input: NexusGenInputs['LoginInput']; // LoginInput!
    }
    register: { // args
      input: NexusGenInputs['RegisterInput']; // RegisterInput!
    }
    removeClassFromClassSchedule: { // args
      input: NexusGenInputs['removeClassFromScheduleInput']; // removeClassFromScheduleInput!
    }
    removeClassFromsemester: { // args
      input: NexusGenInputs['removeClassFromSemesterInput']; // removeClassFromSemesterInput!
    }
    updateClass: { // args
      input: NexusGenInputs['UpdateClassInput']; // UpdateClassInput!
    }
    updateClassSchedule: { // args
      input: NexusGenInputs['updateClassScheduleInput']; // updateClassScheduleInput!
    }
    updateDegree: { // args
      input: NexusGenInputs['updateDegreeInput']; // updateDegreeInput!
    }
    updateSemester: { // args
      input: NexusGenInputs['updateSemesterInput']; // updateSemesterInput!
    }
    updateTask: { // args
      input?: NexusGenInputs['updateTaskInput'] | null; // updateTaskInput
    }
    updateUserAcademicInfo: { // args
      assignmentCompletionPercentage?: number | null; // Float
      attendancePercentage?: number | null; // Float
      gpa?: number | null; // Float
      id: string; // String!
      takenClassIds?: Array<string | null> | null; // [String]
    }
    updateUserProfile: { // args
      degreeId: number; // Int!
      id: string; // String!
      university: string; // String!
      yearInUniversity: number; // Int!
    }
  }
  Query: {
    getClass: { // args
      id: number; // Int!
    }
    getClassScheduleEntries: { // args
      classScheduleId: number; // Int!
    }
    getDegree: { // args
      id: number; // Int!
    }
    getDegreeRequirements: { // args
      id: number; // Int!
    }
    getSemester: { // args
      id: number; // Int!
    }
    getTasks: { // args
      userId: string; // String!
    }
    getUser: { // args
      id: string; // String!
    }
    getclassSchedules: { // args
      userId: string; // String!
    }
    getdegreePlanners: { // args
      userId: string; // String!
    }
    getsemesters: { // args
      plannerId: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: IMyContext;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}